FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/service ./cmd/ingestion/...

FROM scratch
COPY --from=builder /bin/service /service
USER 65534
ENTRYPOINT ["/service"]
